---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
 annotations:
   kubernetes.io/ingress.class: nginx
   nginx.org/websocket-services: "heatmap-svc"
 name: cheese-ingress
spec:
 rules:
 - host: heatmap.example.com
   http:
     paths:
     - backend:
         serviceName: heatmap-svc
         servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: heatmap-svc
  labels:
    app: heatmap
spec:
  type: NodePort
  selector:
    app: heatmap
    track: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heatmap-blue
  labels:
    app: heatmap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heatmap
      track: blue
  template:
    metadata:
      labels:
        app: heatmap
        track: blue
    spec:
      containers:
      - name: heatmap
        image: dbaltor/heatmap:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: MAP_KEY
          value: 
